### PR TITLE
Change wording of input processing detail

### PR DESCRIPTION
**Pull request by SlyRemarks**
Wording proposed by Bill Thomson

### CODE REVIEW

**Comment by lafrech** [comment]
Hi. I'm afraid you're aiming at the wrong repo.

I'm not sure which one is the right one. [This one](https://github.com/aleszuin/docs) seems slightly more up-to-date, but still pretty old.

**Comment by lafrech** [comment]
Or maybe the docs have been integrated in the software repo: https://github.com/emoncms/emoncms/tree/master/docs ?

**Comment by SlyRemarks** [comment]
Very sorry, thank you for the links.

**Comment by lafrech** [comment]
No pb.

**Pull request closed without merging**
